name: 'Build binary and release'

on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check sources
        uses: actions/checkout@v4
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
      - name: Build release
        run: yes | xmake build
      - uses: actions/upload-artifact@v3
        with:
          name: Executable
          path: build/linux/x86_64/release
